version: "3.9"
networks:
  beverages-api:

services:
  nginx:
    image: nginx:stable
    container_name: nginx_beverages
    ports:
      - '8008:80'
    volumes:
      - ./:/var/www:delegated
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - beverages-api
  mysql:
    image: mysql:8
    container_name: mysql_beverages
    restart: unless-stopped
    tty: true
    ports:
      - "3320:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - beverages-api
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_beverages
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./vendor:/var/www/vendor:cached
    networks:
      - beverages-api

volumes:
  mysql_data:
